### ISSUE TITLE
Race condition for AM335x USB recovery

### ISSUE THREAD

**Issue by niebelm** [bootlin/snagboot#16]
Following problems at my desk (Ubuntu Mate 2020.04)

BOOTP serves SPL image twice

**Comment by rgantois** [comment]
Nice catch! I'm fine with moving the `shutdown` and `server_close` calls to before the tftp session completion check, but could you please keep the `bootp_thread.join()` and associated prints at their original location? The tftp session check can be quite time-sensitive and I don't want to wait for a thread to end before doing it. This should still fix your issue but please tell me if it doesn't.

**Comment by rgantois** [comment]
The changes have been merged and tested.
