### ISSUE TITLE
Incorrect SUDOERS in am335x_usb_setup.sh

### ISSUE THREAD

**Issue by tq-steina** [bootlin/snagboot#19]
The new calculation for `SUDOERS` introduced in commit 112bb486c680850446c6290c3c5ff7b02d09fe4f does not work in my case. It results in  `root` rather than my actual user name.

I call the script like this: `sudo ~/repo/snagboot/src/snagrecover/am335x_usb_setup.sh -s 0525:a4a5`

**Comment by rgantois** [comment]
Could you please tell me what distro you are running? Does the command `sudo echo $(logname)` give you the correct username?

**Comment by rgantois** [comment]
It doesn't seem like anyone is reporting more significantly broken cases for this solution so I'll close this issue.
